version: '3'
services:
  falsk_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: PizzaPastaGang
      MONGO_INITDB_ROOT_PASSWORD: pizzapastagang
      MONGO_INITDB_DATABASE: PizzaPastaGang
    volumes:
      - ./docker/db:/data/db
